### ISSUE TITLE
Add Link to QO-100 Chat-only Webpage

### ISSUE THREAD

**Issue by davecrump** [tomvdb/open_tuner#10]
Many users will want to access the QO-100 chat whilst also using Open Tuner.  Currently most of them open a browser with the QO-100 spectrum and chat displayed, which means that they are taking 2 feeds from Goonhilly, increasing both the server and user's bandwidth usage.

Please could you add a button to open the QO-100 chat-only web-page [https://eshail.batc.org.uk/wb/chat/](url) in a new window.  Perhaps underneath the Media Control panel?

**Comment by tomvdb** [comment]
Hi Dave,

Actually I'm busy adding the chat directly into open tuner, similar to what I did with the Rob's quick tune.

T
