### ISSUE TITLE
Device Detection MiniTiouner-Express and -S

### ISSUE THREAD

**Issue by JayCeeSharp** [tomvdb/open_tuner#11]
Hi Tom,
tnx for very fast response (rightclick TX-freq.)!

I found this devicenames corresponding to my tiouners.

((more cosmetic: 
Minitiouner-Express does not allow change of supply voltages.
LNB-Suppy could be hidden.)))

73
Chris

changes to ftdi.cs:

                    if (deviceName.Contains("MiniTiouner A"))  //dh3cs c=0
                    {
                        Console.WriteLine("Should be the i2c port for a Minitiouner-S");
                        i2c_port = c;
                        detectedDeviceName = "Minitiouner-S ";   // dh3cs "Minitiouner Express";
                    }

                    if (deviceName.Contains("MiniTiouner B"))  //dh3cs c=1
                    {
                        Console.WriteLine("Should be the ts port for a Minitiouner-S");
                        i2c_port = c;
                    }

                    if (deviceName.Contains("MiniTiouner-Express A"))   //dh3cs c=0
                    {
                        Console.WriteLine("Should be the i2c port for a Minitiouner Express");
                        ts_port = c;
                        detectedDeviceName = "MiniTiouner-Express";  // dh3cs added line
                    }

                    if (deviceName.Contains("MiniTiouner-Express B"))   //dh3cs c=1
                    {
                        Console.WriteLine("Should be the ts port for a Minitiouner Express");
                        ts_port = c;
                    }

**Comment by tomvdb** [comment]
Based on the logs from Jaap (https://github.com/tomvdb/open_tuner/issues/6), it seems to be as follow:

MiniTiouner A
MiniTiouner B

MiniTiouner-Express A
MiniTiouner-Express B

I'll update accordingly, thanks Chris

**Comment by JayCeeSharp** [comment]
in the meantime I updated the comment - that's correct.
I was a little bit confused,while both devices connected at the same time

**Comment by tomvdb** [comment]
This should be resolved in the latest version, we can re-open if still an issues. Thanks for the feedback :)

T
