### ISSUE TITLE
Widebandchat for old OM (variable fontsize)

### ISSUE THREAD

**Issue by JayCeeSharp** [tomvdb/open_tuner#19]
Hi Tom,
fontsize 8 is a little bit to small for me and maybe for others.
I would change call-split part to 10.
What about using RichTextBox for chat box instead ListBox.
RichTextBox enables fontsize change by CTRL mousewheel.

looks like this for example 
![grafik](https://user-images.githubusercontent.com/35350669/227318983-82dad388-0ad9-472b-bfd9-cdf934e3169a.png)

73
Chris

        public static void AddRTFItem(RichTextBox RB, Object obj)
        {
            if (RB.InvokeRequired)
            {
                UpdateRBDelegate ulb = new UpdateRBDelegate(AddRTFItem);
                RB.Invoke(ulb, new object[] { RB, obj });
            }
            else
            {
                Int32 maxTextLen = 100000;
                if (RB.Text.Length > maxTextLen)
                {
                    RB.Text = RB.Text.Substring(maxTextLen/10,RB.Text.Length/10*9);  //not by row, but quick and dirty
                }

                RB.Text += obj.ToString() + Environment.NewLine;
                // set the current caret position to the end
                RB.SelectionStart = RB.Text.Length;
                // scroll it automatically
                RB.ScrollToCaret();
            }
        }

**Comment by JayCeeSharp** [comment]
that works - didn't read the manual. :-)
what about the idea to click on the user at the left and go to the last line, where the user is mentioned in the chat. I have the code in another project (but for RichTextbox, where I can marked hits it with color)

**Comment by tomvdb** [comment]
Yeah, I like it, I'll put it on the list, just want to sort out a few more higher priority stuff first. Thanks Chris

**Comment by G0MJW** [comment]
An issue with the chat, it remembers your nickname but wants you to change it each time. With a larger font word wrap doesn't seem to be working. Would it be possible to justify the nickname and chat into columns?

**Comment by tomvdb** [comment]
![image](https://user-images.githubusercontent.com/1420347/236484823-3c37d791-6327-40ec-bd4f-255c49d3f70e.png)

Converted to RTB, wordwrapping, better look and clickable links

Will be in next version,
73,
Tom
