### ISSUE TITLE
Windowsize, menusize, spectrumsize, position, audiolevel - would be nice if they were remembered or configured in INI File

### ISSUE THREAD

**Issue by DL2GHM** [tomvdb/open_tuner#22]
Dear Tom,

as i am using more than one instance of your Opentuner and i like to start the software with all my other qo100 Software via an batch file it would be on my wishlist to remember the settings for restart...

Thank you for your excellence work! 

Best regards!
Martin
(DL2GHM)

**Comment by tomvdb** [comment]
The audio levels get stored automatically, but I'll add the rest on the list as well

T

**Comment by DL2GHM** [comment]
Hi Tom,

thank you very much for adding my wishes to the list….

Best regards.
Martin

Von: Tom Van den Bon ***@***.***>
Gesendet: Sonntag, 26. März 2023 15:32
An: tomvdb/open_tuner ***@***.***>
Cc: DL2GHM ***@***.***>; Author ***@***.***>
Betreff: Re: [tomvdb/open_tuner] Windowsize, menusize, spectrumsize, position, audiolevel - would be nice if they were remembered or configured in INI File (Issue #22)


The audio levels get stored automatically, but I'll add the rest on the list as well

T

**Comment by tomvdb** [comment]
Implemented in latest code, will be part of the release this weekend :)
