### ISSUE TITLE
Volume Control via Mouswheel would be nice to have.

### ISSUE THREAD

**Issue by DL2GHM** [tomvdb/open_tuner#23]
Dear Tom,

as i am using Opentuner with maximum picture and minimum menu it would be nice if i can control the audio level via mousewheel while the arrow is over the received picture.

Best regards.
Martin
(DL2GHM)

**Comment by tomvdb** [comment]
hmm, similar to how VLC works. Good idea, I'll look into it :)

**Comment by DL2GHM** [comment]
TNX! :-)

**Comment by tomvdb** [comment]
Implemented in latest code, will be part of the release this weekend :)
