### ISSUE TITLE
16:9 / 4:3 aspect ratio

### ISSUE THREAD

**Issue by py2rn** [tomvdb/open_tuner#25]
Some transmissions use unusual resolution scale and it may cause 4:3 aspect ratio but actually it should show 16:9, could we have an option to select it? 

Thanks

Ed PY2RN

**Comment by tomvdb** [comment]
Hi Ed,

I'll look into it. Any chance you can record some of these transmissions for testing ?

Thanks,
Tom

**Comment by py2rn** [comment]
Hi Tom, yes, that happened yesterday with CT1ZX, he is using portsdown, I will schedule with him and record.
Tks
Ed

    On Monday, March 27, 2023 at 03:15:34 PM GMT-3, Tom Van den Bon ***@***.***> wrote:  
 
 


Hi Ed,

I'll look into it. Any chance you can record some of these transmissions for testing ?

Thanks,
Tom

**Comment by tomvdb** [comment]
Implemented in latest code, will be part of the release this weekend :)

**Comment by py2rn** [comment]
Thanks Tom, you are super!

    On Friday, March 31, 2023 at 03:38:23 PM GMT-3, Tom Van den Bon ***@***.***> wrote:  
 
 


Implemented in latest code, will be part of the release this weekend :)
