### ISSUE TITLE
DVB-S reporting

### ISSUE THREAD

**Issue by G3GJA** [tomvdb/open_tuner#27]
D report does not work with DVB-S.

OK with DVB-S2

Clive G3GJA

**Comment by tomvdb** [comment]
Hi Clive, 

I will check it out. 

T

**Comment by tomvdb** [comment]
Hi Clive, 

I'm not seeing any obvious issues in the code around this. Can you send me a screenshot of where its locking on a DVB-S signal, but not showing the D, maybe there is a clue on there. I'll have to setup something to test a dvb-s signal, will try it out over the weekend.

T

**Comment by PA0RWE** [comment]
Hi,
Yes I found the same problem with DVB-S (from my Portsdown.) Also 125k decoding doesn't seem to work. I tested it on different frequencies but none of the 125K worked. However, lower and higher symbol rates are no problem.

**Comment by PA0RWE** [comment]
Here is a screenshot with no D info.
![2023-04-16 (1)](https://user-images.githubusercontent.com/130929248/232335780-e0030b87-0ad5-4f4d-a866-513be6c3b655.png)

**Comment by PA0RWE** [comment]
Hi,  the screen trying to read 125Ks.

![2023-04-17](https://user-images.githubusercontent.com/130929248/232481965-65b50266-8ec6-4ea6-961c-fa15d0a0d246.png)

**Comment by tomvdb** [comment]
> Hi Clive,
> 
> I'm not seeing any obvious issues in the code around this. Can you send me a screenshot of where its locking on a DVB-S signal, but not showing the D, maybe there is a clue on there. I'll have to setup something to test a dvb-s signal, will try it out over the weekend.
> 
> T

Hi Clive, I have found the problem and it will be resolved in the new version :)

T

**Comment by tomvdb** [comment]
> Hi, the screen trying to read 125Ks.
> 
> ![2023-04-17](https://user-images.githubusercontent.com/130929248/232481965-65b50266-8ec6-4ea6-961c-fa15d0a0d246.png)

Thanks for the screenshot. I will look into it, but please create a new issue the 125ks problem, otherwise it will get lost :)

Thanks for the feedback,
73
Tom

**Comment by tomvdb** [comment]
The reporting on DVB-S should be resolved now on latest version - 0.7 (2023/04/28) Let me know if not correct.

**Comment by PA0RWE** [comment]
Yes, it's OK now. Thanks!
