### ISSUE TITLE
Size of Menu-Bar and Size of Spectrum are not remembered

### ISSUE THREAD

**Issue by DL2GHM** [tomvdb/open_tuner#31]
Dear Tom,

thanks for implementing the size and position variables.
still missing the menu size (0) and Spectrum size...

Best regards
Martin

**Comment by DL2GHM** [comment]
Thank you very much. That would be great!
Best regards
Martin

**Comment by dogastus** [comment]
Would it be possible to translate the text in the wideband chat? It's often in German and it would be useful to understand what they are saying without having to cut and paste into Google translate.

**Comment by DL2GHM** [comment]
Hi Nigel,

that is a good idea! And it is worth to make it to its own issue (better not to mix different ideas - it is easier to separate them because they would be easier to close them one by another...)

**Comment by dogastus** [comment]
> Hi Nigel,
> 
> that is a good idea! And it is worth to make it to its own issue (better not to mix different ideas - it is easier to separate them because they would be easier to close them one by another...)

Sorry, I don't use Github very often. I've created a new topic now and will delete the entry here.

**Comment by tomvdb** [comment]
The splitter distance for the tuner/menu bar is now part of the settings and will be saved same as window width/height sizes when app is closed. Will be in next version :)
