### ISSUE TITLE
Two other ideas... Overlaying D and MER while mouse over. And Overlaying Volume while changing with mouswheel...

### ISSUE THREAD

**Issue by DL2GHM** [tomvdb/open_tuner#32]
Dear Tom,
two other ideas. Perhaps you find it useful too ;-)

It would be smart to overlay the D and MER values while mouse over Video. (As in fullscreen mode)

Also it would be nice to overlay the volume amount while changing. Perhaps for one or two seconds.

By the way - is it possible to change the volume steps to 5% and perhaps with shift mousewheel to 1% steps...

That would be smart! 
And for those who don't want to be disturbed by overlays - perhaps it is comfortable to make it switchable via config file.

Thank you very much for the very good work you have done!
Wish you happy easter!

Best regards
Martin
(DL2GHM)

**Comment by tomvdb** [comment]
Hi Martin,

Will be part of next release. The following has been added:

Use mousewheel to adjust volume with visual indicator (bar on right) - indicator shows for 2 sec when volume is changed via mousewheel.
Double click video to enable an overlay showing db margin, mer, callsign, freq and symbol rate - works on normal view and seperate window view

![image](https://github.com/tomvdb/open_tuner/assets/1420347/df408f34-ee37-4a58-b57e-bf274bcd945e)

Inspired/Motivated by this fork (https://github.com/SV8ARJ/open_tuner) ;)

73,
Tom
