### ISSUE TITLE
Add a button to update carrier frequency offset

### ISSUE THREAD

**Issue by dogastus** [tomvdb/open_tuner#34]
It would be nice to have a feature where the carrier frequency offset setting was updated using the difference in frequency between what was requested and what was measured.

Also, it would be good if the updated offset frequency was applied immediately. At the moment, changing the offset frequency in Settings requires a restart of the program for it to take effect.

**Comment by tomvdb** [comment]
Latest version has an adjust feature which takes into account the carrier offset. Will be in release this week.

I'll add something for offset frequency adjust

**Comment by tomvdb** [comment]
Latest version with the Adjust link is out, let me know if any issues.
