### ISSUE TITLE
TS Status Led's

### ISSUE THREAD

**Issue by g6hfs** [tomvdb/open_tuner#35]
Hi, Tom,

Is it possible to enable led on/off status for TS1/TS2 and LNB A/B volts

Brian (G6HFS)

**Comment by tomvdb** [comment]
TS1/TS2 Leds should work with latest version :)

**Comment by g6hfs** [comment]
Thanks Tom, also what about adding back the default select on start station73Brian (G6HFS)On 19 Sep 2023, at 10:25, Tom Van den Bon ***@***.***> wrote:﻿
TS1/TS2 Leds should work with latest version :)
