### ISSUE TITLE
Service Name Provider

### ISSUE THREAD

**Issue by F1EJP** [tomvdb/open_tuner#38]
Tom,
it's seem that Service Name Provider is not the correct parameter in DVB table ?
It is not the same as the one displayed in Longmynd or Minitiouner

(I Give you the French traduction in your old post)
73
Dominique F1EJP

**Comment by tomvdb** [comment]
Hi Dominique

Interesting, I will need to investigate this. I'll get back to you.

Thanks,
T

**Comment by tomvdb** [comment]
Hi Dominique, I can't seem to find any issues with this and nobody else has complained about this yet. I'm going to close this issue for now and we'll see if it pops up again. Feel free to open the issue again if you have any insights as to what may be happening.
