### ISSUE TITLE
Tuner Input B cannot be selected.

### ISSUE THREAD

**Issue by G8YTZ** [tomvdb/open_tuner#39]
New issue for v0.7

In setup both A & B are set to zero offset.

In Memory:
Freq = 1746000
Offset = 0
Symbol Rate = 2000
RF Input = B
Default Tuner = 1

As it's a strong signal there is bleed-over between the inputs, selecting the wrong input (A) reception is possible with a weaker signal.

Previous version was ok, Minitioune is ok (just tested to confirm it is not a Minitiouner issue)

**Comment by g6hfs** [comment]
No problem with Minitiouner Pro 2

**Comment by G8YTZ** [comment]
Interesting. Mine is the BATC Minitiouner. Previous version was fine, so something has changed.

**Comment by G8YTZ** [comment]
Tom, here is a video link (Unlisted YouTube) From the time of writing 10:13 UTC  it will take 60 minutes or so to process to 4k.

[https://youtu.be/sKqBP1yjdwQ](url)

**Comment by g6hfs** [comment]
Strange, pro 2 ok even ffmpeg with vvch266

![Opentuner 2_Original](https://user-images.githubusercontent.com/108218059/235125128-0d0c23e9-9edc-4448-bb17-0e27db33b8ac.jpeg)

**Comment by G8YTZ** [comment]
That's with RF Input A though. The issue is with Input B

**Comment by g6hfs** [comment]
Sorry wrong picture, now with A and B on local repeater 

![IMG_0787](https://user-images.githubusercontent.com/108218059/235130237-35bd83d6-3d52-4571-8545-68c9c968a734.jpeg)

**Comment by G8YTZ** [comment]
The video link above is active now, best select 4k. I'm using a single Tuner Minitiouner without second TS board, perhaps you're using something else?

**Comment by G8YTZ** [comment]
Brian,

thanks for confirming my cognitive health! :-)

Justin

**Comment by tomvdb** [comment]
Thanks guys, I managed to trace down this issue. I will be sorted in the next version.

**Comment by G8YTZ** [comment]
Tom, that’s great! I’ll test tomorrow and report back.
Justin

**Comment by g6hfs** [comment]
Has Tom released the next version?

**Comment by g6hfs** [comment]
Yes, works OK here on minitiouner v2 from the batc

Brian

**Comment by G8YTZ** [comment]
Hi Tom, I can confirm that Input A & B switching now works with the Minitiouner V2, however there is an issue again with the IF Offset that was fixed in an earlier release (01/04/23) e.g. Rx 3404000, LO 5150000 No reception. It might be that you need to specify a +ve or =ve offset. I'll post a new issue.
Basically I currently use 3 LOs
9750MHz - QO100
5150MHz - C-Band LNB for 9cm
929MHz  - IC-9700 23cm Ist IF when using Radio Analog board PTRX9700 for 23cm reception

**Comment by tomvdb** [comment]
Cool, I'll look into it. Latest version 7c is now on website with Input fix.
