### ISSUE TITLE
Error in negative MER calculation

### ISSUE THREAD

**Issue by G0MJW** [tomvdb/open_tuner#51]
This is an signed int, but your code is using an unsigned int thinking it can't be negative, but it can. Here is Dave's modified Portsdown Longmynd code:

uint8_t stv0910_read_mer(uint8_t demod, int32_t *mer) {
/* -------------------------------------------------------------------------------------------------- */
/*    demod: STV0910_DEMOD_TOP | STV0910_DEMOD_BOTTOM: which demodulator is being read                */
/*      mer: place to store the result                                                                */
/*   return: error state                                                                              */
/* -------------------------------------------------------------------------------------------------- */
    uint8_t err;
    uint8_t high, low;

                         err=stv0910_read_reg(demod==STV0910_DEMOD_TOP ? RSTV0910_P2_NOSRAMPOS : RSTV0910_P1_NOSRAMPOS, &high);
    if (err==ERROR_NONE) err=stv0910_read_reg(demod==STV0910_DEMOD_TOP ? RSTV0910_P2_NOSRAMVAL : RSTV0910_P1_NOSRAMVAL, &low);

    if(((high >> 2) & 0x01) == 1)
    {
        /* Px_NOSRAM_CNRVAL is valid */
        if(((high >> 1) & 0x01) == 1)
        {
            /* Negative */
            *mer = (((high & 0x01) << 8) | low) - 512;
        }
        else
        {
            *mer = ((high & 0x01) << 8) | low;
        }
        
    }
    else
    {
        *mer = 0;
        if (err==ERROR_NONE) err=stv0910_write_reg_field(demod==STV0910_DEMOD_TOP ? FSTV0910_P2_NOSRAM_ACTIVATION : FSTV0910_P1_NOSRAM_ACTIVATION, 0x02);
    }

    if (err!=ERROR_NONE) printf("ERROR: STV0910 read DVBS2 MER\n");

    return err;
}

In your code (which is in c# so not the same, you don't deal with the negative MER and assign it to an unsiged int.

 public byte stv0910_read_mer(byte demod, ref UInt32 mer)
        {
            byte err = 0;
            byte high = 0;
            byte low = 0;

            err = stv0910_read_reg(demod == STV0910_DEMOD_TOP ? stv0910_regs.RSTV0910_P2_NOSRAMPOS : stv0910_regs.RSTV0910_P1_NOSRAMPOS, ref high);
            if (err == 0) err = stv0910_read_reg(demod == STV0910_DEMOD_TOP ? stv0910_regs.RSTV0910_P2_NOSRAMVAL : stv0910_regs.RSTV0910_P1_NOSRAMVAL, ref low);

            if (((high >> 2) & 0x01) == 1)
            {
                /* Px_NOSRAM_CNRVAL is valid */
                mer = (uint)(((high & 0x03) << 8) | low);
            }
            else
            {
                mer = 0;
                if (err == 0) err = stv0910_write_reg_field(demod == STV0910_DEMOD_TOP ? stv0910_regs.FSTV0910_P2_NOSRAM_ACTIVATION : stv0910_regs.FSTV0910_P1_NOSRAM_ACTIVATION, 0x02);
            }

            if (err != 0) Console.WriteLine("ERROR: STV0910 read DVBS2 MER\n");

            return err;

        }

**Comment by tomvdb** [comment]
Sorted, thanks Mike.
