### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by G0MJW** [tomvdb/open_tuner#53]
Latest version 0.7f has no sound on my system. It works with others. This was not an issue with the earlier version. The earlier version still works fine, so it must be in a change made in version f. This is an AMD system which might mean you are using audio codec extensions that are not supported.

**Comment by 9H1LO** [comment]
same here no audio, don't have previous version to test, system is not AMD like G0MJW, tried on 2 different PC's same issue with audio

**Comment by tomvdb** [comment]
Hi Mike,

Are you still having these issues with the latest version ?

T

**Comment by G0MJW** [comment]
I have not tried Tom. I have been mostly working.

 

Mike

**Comment by tomvdb** [comment]
Cool, I'm closing this issue for now. Feel free to reopen if still an issue.

T
