### ISSUE TITLE
Network binding

### ISSUE THREAD

**Issue by 9H1LO** [tomvdb/open_tuner#56]
is the network binding for UDP stream only to the local interface ? changed the ip under settings to local ip instead on 127.0.0.1, but can only get VLC to pull the UDP TS on the local machine, no-go over the network

**Comment by tomvdb** [comment]
This should work over the network as well, make sure your windows firewall is not blocking it. Usually UDP issues like this is related to the firewall. Let me know if still having issues then we can try to troubleshoot.

T

**Comment by tomvdb** [comment]
I'm closing the issue, feel free to reopen if still having issues
