### ISSUE TITLE
V 0.8 Window open separately, but not set in settings

### ISSUE THREAD

**Issue by Rolf-L** [tomvdb/open_tuner#59]
Hi Tom,
testing version 0.8. When selecting a station, it was not displayed in the 2nd window below the 1st window, but the 2nd window was opened separately, even though separate windows were not selected in the Media settings (VLC-Mode). I could move the window and change the size, but I couldnt close it. After starting OT again, this effect was no longer noticeable.
Update:
today (03.10.23) I had this effect again, selecting A71A to place it in the second window too.
I'm using Win 10, two displays and a Nvidia GTX 1650. See below...
73 de Rolf -DJ7TH-

![WhatsApp Bild 2023-10-03 um 11 52 01_cc570cf4](https://github.com/tomvdb/open_tuner/assets/7458260/97db3494-4356-4319-bfae-fda3028cb215)

![WhatsApp Bild 2023-10-03 um 11 52 01_e4b410a8](https://github.com/tomvdb/open_tuner/assets/7458260/c4217017-d6f0-44bc-a40d-3489a75d148f)

**Comment by tomvdb** [comment]
Hi Rolf,

I think I have fixed this in the latest version. Its a pesky bug, I have a new version coming in the next few days then we can see if still persists.

T

**Comment by tomvdb** [comment]
Resolved :)
