### ISSUE TITLE
OT 0.9

### ISSUE THREAD

**Issue by g6hfs** [tomvdb/open_tuner#66]
Tom,

0.9 of OT has a fixed window position, and can not move to different area 

Brian

**Comment by dead-fets** [comment]
Not seeing this on my PC Brian, can move, re size and do all the usual. Win 10 l64 bit, with latest updates.

**Comment by g6hfs** [comment]
Tom Thanks,Will look into the issue here, also on another note selecting auto tune on either stream selects rx 1,2 together and not individually 73Brian (G6HFS)On 11 Feb 2024, at 14:48, dead-fets ***@***.***> wrote:﻿
Not seeing this on my PC Brian, can move, re size and do all the usual. Win 10 l64 bit, with latest updates.

**Comment by g6hfs** [comment]
Tom Update,Seems first issue was finger trouble, sorry about that but rx 1,2 selects both still73Brian (G6HFS)On 11 Feb 2024, at 14:48, dead-fets ***@***.***> wrote:﻿
Not seeing this on my PC Brian, can move, re size and do all the usual. Win 10 l64 bit, with latest updates.
