### ISSUE TITLE
Nullpackets as bargraph

### ISSUE THREAD

**Issue by JayCeeSharp** [tomvdb/open_tuner#7]
Hi Tom,

what about a "progressbar" showing Null Packets.
(Tried to upload picture - I'm a newbie here)

73
Chris, dh3cs
![grafik](https://user-images.githubusercontent.com/35350669/226473218-f58c0696-3e01-4233-b237-a5bdbbc1f69d.png)

**Comment by tomvdb** [comment]
Implemented, will be part of the new release :)
