### ISSUE TITLE
OpenTuner, lnb control for pi pico

### ISSUE THREAD

**Issue by g6hfs** [tomvdb/open_tuner#72]
No control of lnb bias for pi pico control, ok with portsdown 4.

Brian

**Comment by tomvdb** [comment]
added in latest version

**Comment by g6hfs** [comment]
Hi Tom, May I have link to latest version to test please.Brian
-------- Original message --------From: Tom Van den Bon ***@***.***> Date: 08/04/2024  14:55  (GMT+00:00) To: tomvdb/open_tuner ***@***.***> Cc: g6hfs ***@***.***>, Author ***@***.***> Subject: Re: [tomvdb/open_tuner] OpenTuner, lnb control for pi pico (Issue
  #72) 
added in latest version

**Comment by g6hfs** [comment]
Hi Tom,May I have a copy of latest ooentune to beta test please.BrianG6HFSSent from my Galaxy S20 5G
