### ISSUE TITLE
Opentuner/PicoTuner

### ISSUE THREAD

**Issue by g6hfs** [tomvdb/open_tuner#73]
Version 09/0A both leave ts1/2 leds on when opentuner closed.

Brian

**Comment by tomvdb** [comment]
using what hardware ? picotuner or ftdi ?

**Comment by g6hfs** [comment]
Hi Tom,Using Picotuner
-------- Original message --------From: Tom Van den Bon ***@***.***> Date: 08/04/2024  14:55  (GMT+00:00) To: tomvdb/open_tuner ***@***.***> Cc: g6hfs ***@***.***>, Author ***@***.***> Subject: Re: [tomvdb/open_tuner] Opentuner/PicoTuner (Issue #73) 
using what hardware ? picotuner or ftdi ?

**Comment by tomvdb** [comment]
For future reference for others looking here, the pico tuner controls those led's from the hardware, I can only control them on the ftdi versions. the led's stay on when app is closed, because the picotuner is still receiving ts data.

T
