### ISSUE TITLE
Feature request: AUTOMUTE function on startup

### ISSUE THREAD

**Issue by DL2GHM** [tomvdb/open_tuner#77]
Would be nice to AUTOMUTE all channels when starting up. CW Beacon Volume nearly kills the speakers sometimes after restarting.
Best regards DL2GHM

**Comment by dl1rf** [comment]
I am working on this issue within my fork.
Goal is to save the mute and premute states within the settings.

**Comment by DL2GHM** [comment]
Thank you for the info…

Von: Martin ***@***.***>
Gesendet: Sonntag, 14. April 2024 10:40
An: tomvdb/open_tuner ***@***.***>
Cc: DL2GHM ***@***.***>; Author ***@***.***>
Betreff: Re: [tomvdb/open_tuner] Feature request: AUTOMUTE function on startup (Issue #77)


I am working on this issue within my fork.
Goal is to save the mute and premute states within the settings.

**Comment by tomvdb** [comment]
Thanks Martin, PR has been merged. I'm fixing a few other things and will then do another release in the next couple of days.

T

**Comment by DL2GHM** [comment]
Thank you very much!
Especially for the last feature. It is important because it is also working after restarting after a crash.
73 de DL2GHM
Maritn

Von: Martin ***@***.***>
Gesendet: Dienstag, 16. April 2024 16:44
An: tomvdb/open_tuner ***@***.***>
Cc: DL2GHM ***@***.***>; Author ***@***.***>
Betreff: Re: [tomvdb/open_tuner] Feature request: AUTOMUTE function on startup (Issue #77)


The feature implementation is finished.
The following functionality will be provided:
Mute Button will go to red if muted.
Mute state and volume state before mute will be saved on program exit.
A new check box at settings page will force mute at startup if checked.

vy 73 de Martin, DL1RF

**Comment by tomvdb** [comment]
Closing Issue, this functionality is now all in 0.B thanks to Martin (DL1RF) - Feel free to create a new issue if I missed something.

**Comment by DL2GHM** [comment]
👍



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Tom Van den Bon ***@***.***>
Datum: 09.07.24 10:47 (GMT+01:00)
An: tomvdb/open_tuner ***@***.***>
Cc: DL2GHM ***@***.***>, Author ***@***.***>
Betreff: Re: [tomvdb/open_tuner] Feature request: AUTOMUTE function on startup (Issue #77)


Closing Issue, this functionality is now all in 0.B thanks to Martin (DL1RF) - Feel free to create a new issue if I missed something.
