### ISSUE TITLE
OT 0.A: Dutch language settings

### ISSUE THREAD

**Issue by ON1AVO** [tomvdb/open_tuner#78]
Hi Tom,

When running OT0.A with preferred language settings in Dutch the Main settings translating is partly wrong, see screenshot.
![OT0_A](https://github.com/tomvdb/open_tuner/assets/132191313/01206e09-cf5e-40dd-a2a2-1a2c79f32291)

**Comment by ON1AVO** [comment]
I deleted all the files in %userprofile%\appdata\local\Amateur_Radio_-_ZR6TG, no luck

**Comment by tomvdb** [comment]
Hi,

Thanks for letting me know. This is still some leftovers from the original languages that were put in. I'll spend some time and clean it up.

T

**Comment by tomvdb** [comment]
This should now all be resolved in the 0.B version - Thanks! Closing Issue, feel free to re open if something else is found.

73,
Tom
