### ISSUE TITLE
Opentuner 0-A starts then crashes, log file linked

### ISSUE THREAD

**Issue by dead-fets** [tomvdb/open_tuner#79]
OT 0-A worked fine for about two days, now it launches and upon pressing connect button crashes. Log file is available at http://www.chriswilson.tv/log.zip

I tried deleting this version and re-installing. I *THINK* the trouble starts when changing the order of decoders from the default, or changing the saved recordings / snapshots folder.

EDIT, works fine with all default settings. I change the first decoder  from VLC to FFMPEG and on relaunch it crashes on pressing the Connect button. Repeatable.

Thanks Tom.

**Comment by DL2GHM** [comment]
Same issue in my three installations of OT 0A. Setting up to ffmpeg results in crash after 2 seconds.

**Comment by tomvdb** [comment]
Thanks, I'll have a look at this today. It definitely helps to have a reproducible problem. Will have feedback tonight

**Comment by tomvdb** [comment]
Closing this as all should be good with the new 0.B version, let me know if these crashes still happen
