### ISSUE TITLE
Opentuner 0.B 20240707

### ISSUE THREAD

**Issue by G8YTZ** [tomvdb/open_tuner#94]

**Comment by tomvdb** [comment]
Hi Justin, did you come right? The description of this ticket is currently empty ?

T

**Comment by G8YTZ** [comment]
Yes,

I had an issue, but it turned out to be ports. I wanted to delete the comment, but could not.

The software is working well, very stable on Ethernet too.

Best regards,

Justin Cockett
***@***.***
www.gb3jv.co.uk <http://www.gb3jv.co.uk/>

**Comment by tomvdb** [comment]
Glad to hear, I'll close the ticket. Thanks Justin.

T

**Comment by G8YTZ** [comment]
Sent from my Remington Rand UNIVACwww.g8ytz.com On 8 Jul 2024, at 08:03, Tom Van den Bon ***@***.***> wrote:﻿
Glad to hear, I'll close the ticket. Thanks Justin.
T
