### ISSUE TITLE
2 minor issues with B test release

### ISSUE THREAD

**Issue by dead-fets** [tomvdb/open_tuner#97]
The station call sign does not appear to display above signals in the wide band monitor window anymore. 

I tried adding AUTOCONNECT in the shortcut, which has worked for other versions, and also tried adding it in the *.json file as true rather than false, but it still needs manually connecting.

As I said, both minor, but as I spotted them I thought I'd mention them Tom, thanks again.

**Comment by tomvdb** [comment]
Hi Chris,

Thanks, callsigns issue has been resolved.

The autoconnect functionality (https://github.com/tomvdb/open_tuner/issues/76) is on the list and I'll add it back soon.

73,
Tom
