### ISSUE TITLE
Chat signal report shows DD instead of just D

### ISSUE THREAD

**Issue by dead-fets** [tomvdb/open_tuner#98]
I am pretty sure it never used to do that? I recall the sig report just showed D*

Now it shows DD.  I'm sure there's a joke in there somewhere....   ;)

![double-d](https://github.com/tomvdb/open_tuner/assets/132020826/2a1a3718-c7f0-495d-a028-e9a990f9d87d)

**Comment by tomvdb** [comment]
there is some inconsistencies between the different sources and how they pass the data. what hardware are you using in this example ?

**Comment by tomvdb** [comment]
Chris, if you have my email, can you send me a direct email please. Have something else I want to test :)

T

**Comment by dead-fets** [comment]
I am using Minitiouner with two FTDI modules.

I don't have your direct mail Tom, but if you fire *me* a mail at chris at chriswilson.tv I will have? Cheers.

**Comment by tomvdb** [comment]
This should be sorted :)

73,
Tom
