### ISSUE TITLE
MER incorrect in new DATV Spotter

### ISSUE THREAD

**Issue by dead-fets** [tomvdb/open_tuner#99]
I *THINK* I see what's happening Tom. If I select both tuners (FTDI x 2 in Minitiouner) the MER upload is from the wrong tuner for one of the receivers, IYSWIM? 

Select only one Rx and MER and D are correct. Select *BOTH* receivers and the MER is correct for one tuner, but that MER figure is also presented as if from the other tuner, too.  

Maybe.... ;)

EDIT: Yes, it presents the MER figure from Rx1 / Tuner 1  to RX2 / Tuner 2 as well if both are in use.

Further confirmation: If an RX1 station goes off air the MER that RX 2 then uploads is 0.00

**Comment by tomvdb** [comment]
Thanks Chris, the version I sent this morning should have resolved this. Let me know if still having an issue.

73,
Tom
